### ISSUE TITLE
Some issue

### ISSUE THREAD

**Issue by Johnnywick1** [omrfrkcpr/iweather#2]
Hi,

I think there is an issue with Probability of rain. When it shows 1% it should be 100%. When it shows 0,09% should be 9%. 

Check it please

Thank you

**Comment by omrfrkcpr** [comment]
Hi,

I really missed this situation. It has now been corrected. Thank you very
much for contributing to my project.

Best Regards,
Omer

Am Do., 4. Apr. 2024 um 08:57 Uhr schrieb Johnnywick1 <
***@***.***>:
