### ISSUE TITLE
Favorites

### ISSUE THREAD

**Issue by SelvBerkay** [omrfrkcpr/iweather#3]
Selam, 

Favorilerdeki şehirlerin sıcaklık değerlerinin birimi, son eklediğin şehrin metric seçimine göre güncelleniyor. Ortaya absürt sıcaklık değerleri çıkıyor.

Kontrol edebilirsin 😄 

İyi çalışmalar.

**Comment by omrfrkcpr** [comment]
Merhabalar,

Öncelikle projeme gösterdiğin ilgi ve desteğin için teşekkür ederim. Aslında bu şekilde olmasının sebebi, sıcaklık biriminin kullanıcının günlük hayatta kullandığı constant bir değer olduğunu düşünmemdi. Bu nedenle kullanıcının aradığı yere göre sıcaklık biriminin değişmesinin çok önemli olduğunu düşünmedim. Sence bu konuda nasıl bir mantık olmalıdır? Daha detaylı açıklayabilir misin?

**Comment by SelvBerkay** [comment]
Merhaba,

Sanırım anlaşamadık görselleri aşağıya bırakıyorum öncekikle İstanbul'u Fahrenheit cinsinde arayıp favorilere ekledim ekledim. Daha sonra ise Konya'yı celsius cinsinde aratıp favorilere ekledim. Favorilere girdiğimde ise gördüğün gibi İstanbul için eklediğim cins fahrenheit iken celsius'a dönüyor ve sayılar absürt kalıyor. Ellerine sağlık bu arada gerçekten çok güzel bir proje olmuş.
![image](https://github.com/omrfrkcpr/iweather/assets/137525654/4851546b-1076-427c-8ac2-cb812fefd5d2)
![image](https://github.com/omrfrkcpr/iweather/assets/137525654/c609119c-efbf-4366-9a78-4144fc07173b)
![image](https://github.com/omrfrkcpr/iweather/assets/137525654/f47171f4-7866-4baa-adb1-938e92cc7ae7)

**Comment by SelvBerkay** [comment]
Bu arada constant değer konusunda hemfikiriz.

**Comment by omrfrkcpr** [comment]
Tamamdır şimdi problemi anlayabildim. En kısa zamanda gerekli düzeltmeleri yapıcam. Teşekkür ederim tekrar.
